# Generated by Django 4.1.5 on 2023-02-03 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_creacion_tabla_categoria_platos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='platomodel',
            table='platos',
        ),
    ]
