"""Creacion del migrate

Revision ID: 99834f827de0
Revises: 
Create Date: 2023-01-18 22:02:08.221625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99834f827de0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
