"""Creacion de categorias model

Revision ID: a6ede0d82507
Revises: 2e1881eac35d
Create Date: 2023-01-19 21:40:58.532672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ede0d82507'
down_revision = '2e1881eac35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    op.drop_table('categorias')
    # ### end Alembic commands ###
