"""Users

Revision ID: fc0c0b2b46f1
Revises: c042a6399d2d
Create Date: 2023-01-20 22:37:00.325754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0c0b2b46f1'
down_revision = 'c042a6399d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('contrasena', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
